version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    restart: always

  frontend:
    build: ./frontend
    ports:
      - '22288:3000'
    restart: always
